apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-bench-mark-test
  labels:
    app: cpu-bench-mark-test
spec:
  selector:
    matchLabels:
      app: cpu-bench-mark-test
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cpu-bench-mark-test
    spec:
      containers:
      - name: cpu-bench-mark-test
        image: "d2/cpu_bench_mark"
        imagePullPolicy: IfNotPresent
        env: 
        - name: SCRIPT
          value: "numbers_decimal_bigiint_div.js"
        resources:
            limits:
              memory: 250Mi
              cpu: 2200m
            requests:
              cpu: 2000m
              memory: 200Mi
